name: Amazon Deals Cron

on:
  schedule:
   # - cron: '*/15 * * * *'    # alle 15 Minuten
  workflow_dispatch:         # manuelles Auslösen möglich

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies (Chrome + xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper with Xvfb
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: |
          xvfb-run -a python amazon_deals.py
